package ishares

import (
	"sort"

	"github.com/yevklym/etfscraper"
)

type regionConfig struct {
	DiscoveryURL        string
	BaseURL             string
	HoldingsURLTemplate string
	DefaultCurrency     etfscraper.Currency
	DefaultExchange     etfscraper.Exchange
	AssetClassMapping   map[string]etfscraper.AssetClass
	SectorMapping       map[string]etfscraper.Sector
	LocationMapping     map[string]etfscraper.Location
	ColumnMappings      ColumnMapper
	MonthTranslations   map[string]string
	DateFormats         []string
	DateHeaderPatterns  []string
}

type ColumnMapper struct {
	Name           []string
	Ticker         []string
	ISIN           []string
	MarketValue    []string
	Weight         []string
	Quantity       []string
	ParValue       []string // For bonds
	Price          []string
	Sector         []string
	AssetClass     []string
	Location       []string
	Exchange       []string
	Currency       []string
	MarketCurrency []string
}

var regionConfigs = map[string]regionConfig{
	"us": {
		DiscoveryURL:        "https://www.ishares.com/us/product-screener/product-screener-v3.1.jsn?dcrPath=/templatedata/config/product-screener-v3/data/en/us-ishares/ishares-product-screener-backend-config&siteEntryPassthrough=true",
		BaseURL:             "https://www.ishares.com",
		HoldingsURLTemplate: "%s%s/1467271812596.ajax?fileType=csv",
		DefaultCurrency:     etfscraper.CurrencyUSD,
		DefaultExchange:     etfscraper.ExchangeNYSE,
		AssetClassMapping: map[string]etfscraper.AssetClass{
			"equity":         etfscraper.AssetClassEquity,
			"fixed income":   etfscraper.AssetClassBond,
			"cash":           etfscraper.AssetClassCash,
			"commodity":      etfscraper.AssetClassCommodity,
			"real estate":    etfscraper.AssetClassRealEstate,
			"digital assets": etfscraper.AssetClassCryptocurrency,
			"multi asset":    etfscraper.AssetClassAlternative,
		},
		SectorMapping: map[string]etfscraper.Sector{
			"energy":                 etfscraper.SectorEnergy,
			"materials":              etfscraper.SectorMaterials,
			"industrials":            etfscraper.SectorIndustrials,
			"consumer discretionary": etfscraper.SectorConsumerDiscretionary,
			"consumer staples":       etfscraper.SectorConsumerStaples,
			"health care":            etfscraper.SectorHealthcare,
			"financials":             etfscraper.SectorFinancials,
			"information technology": etfscraper.SectorInformationTechnology,
			"communication":          etfscraper.SectorTelecommunication,
			"utilities":              etfscraper.SectorUtilities,
			"real estate":            etfscraper.SectorRealEstate,
		},
		LocationMapping: map[string]etfscraper.Location{
			"united states":           etfscraper.LocationUnitedStates,
			"united kingdom":          etfscraper.LocationUnitedKingdom,
			"japan":                   etfscraper.LocationJapan,
			"germany":                 etfscraper.LocationGermany,
			"france":                  etfscraper.LocationFrance,
			"switzerland":             etfscraper.LocationSwitzerland,
			"canada":                  etfscraper.LocationCanada,
			"australia":               etfscraper.LocationAustralia,
			"china":                   etfscraper.LocationChina,
			"taiwan":                  etfscraper.LocationTaiwan,
			"south korea":             etfscraper.LocationSouthKorea,
			"india":                   etfscraper.LocationIndia,
			"brazil":                  etfscraper.LocationBrazil,
			"netherlands":             etfscraper.LocationNetherlands,
			"sweden":                  etfscraper.LocationSweden,
			"italy":                   etfscraper.LocationItaly,
			"spain":                   etfscraper.LocationSpain,
			"ireland":                 etfscraper.LocationIreland,
			"denmark":                 etfscraper.LocationDenmark,
			"finland":                 etfscraper.LocationFinland,
			"turkey":                  etfscraper.LocationTurkey,
			"belgium":                 etfscraper.LocationBelgium,
			"austria":                 etfscraper.LocationAustria,
			"luxembourg":              etfscraper.LocationLuxembourg,
			"singapore":               etfscraper.LocationSingapore,
			"norway":                  etfscraper.LocationNorway,
			"israel":                  etfscraper.LocationIsrael,
			"cash and/or derivatives": etfscraper.LocationCash,
		},
		MonthTranslations:  nil,
		DateFormats:        []string{"Jan 2, 2006"},
		DateHeaderPatterns: []string{"Fund Holdings as of"},
		ColumnMappings: ColumnMapper{
			Name:           []string{"Name"},
			Ticker:         []string{"Ticker"},
			ISIN:           []string{"ISIN"},
			MarketValue:    []string{"Market Value"},
			Weight:         []string{"Weight (%)", "Market Weight"},
			Quantity:       []string{"Quantity"},
			Price:          []string{"Price"},
			Sector:         []string{"Sector"},
			AssetClass:     []string{"Asset Class"},
			Location:       []string{"Location"},
			Exchange:       []string{"Exchange"},
			Currency:       []string{"Currency"},
			MarketCurrency: []string{"Market Currency"},
		},
	},
	"de": {
		DiscoveryURL:        "https://www.ishares.com/de/privatanleger/de/product-screener/product-screener-v3.1.jsn?dcrPath=/templatedata/config/product-screener-v3/data/de/germany/product-screener/ishares-product-screener-backend-config&siteEntryPassthrough=true",
		BaseURL:             "https://www.ishares.com",
		HoldingsURLTemplate: "%s%s/fund/1478358465952.ajax?fileType=csv",
		DefaultCurrency:     etfscraper.CurrencyEUR,
		DefaultExchange:     etfscraper.ExchangeXetra,
		AssetClassMapping: map[string]etfscraper.AssetClass{
			"aktien":         etfscraper.AssetClassEquity,
			"anleihen":       etfscraper.AssetClassBond,
			"barmittel":      etfscraper.AssetClassCash,
			"rohstoffe":      etfscraper.AssetClassCommodity,
			"immobilien":     etfscraper.AssetClassRealEstate,
			"digital assets": etfscraper.AssetClassCryptocurrency,
			"multi-asset":    etfscraper.AssetClassAlternative,
		},
		SectorMapping: map[string]etfscraper.Sector{
			"energie":                    etfscraper.SectorEnergy,
			"materialien":                etfscraper.SectorMaterials,
			"industrie":                  etfscraper.SectorIndustrials,
			"zyklische konsumgüter":      etfscraper.SectorConsumerDiscretionary,
			"nichtzyklische konsumgüter": etfscraper.SectorConsumerStaples,
			"gesundheitsversorgung":      etfscraper.SectorHealthcare,
			"financials":                 etfscraper.SectorFinancials,
			"it":                         etfscraper.SectorInformationTechnology,
			"kommunikation":              etfscraper.SectorTelecommunication,
			"versorger":                  etfscraper.SectorUtilities,
			"immobilien":                 etfscraper.SectorRealEstate,
		},
		LocationMapping: map[string]etfscraper.Location{
			"vereinigte staaten":        etfscraper.LocationUnitedStates,
			"united states":             etfscraper.LocationUnitedStates,
			"vereinigtes königreich":    etfscraper.LocationUnitedKingdom,
			"united kingdom":            etfscraper.LocationUnitedKingdom,
			"japan":                     etfscraper.LocationJapan,
			"deutschland":               etfscraper.LocationGermany,
			"germany":                   etfscraper.LocationGermany,
			"frankreich":                etfscraper.LocationFrance,
			"france":                    etfscraper.LocationFrance,
			"schweiz":                   etfscraper.LocationSwitzerland,
			"switzerland":               etfscraper.LocationSwitzerland,
			"kanada":                    etfscraper.LocationCanada,
			"canada":                    etfscraper.LocationCanada,
			"australien":                etfscraper.LocationAustralia,
			"australia":                 etfscraper.LocationAustralia,
			"china":                     etfscraper.LocationChina,
			"taiwan":                    etfscraper.LocationTaiwan,
			"südkorea":                  etfscraper.LocationSouthKorea,
			"south korea":               etfscraper.LocationSouthKorea,
			"indien":                    etfscraper.LocationIndia,
			"india":                     etfscraper.LocationIndia,
			"brasilien":                 etfscraper.LocationBrazil,
			"brazil":                    etfscraper.LocationBrazil,
			"niederlande":               etfscraper.LocationNetherlands,
			"netherlands":               etfscraper.LocationNetherlands,
			"schweden":                  etfscraper.LocationSweden,
			"sweden":                    etfscraper.LocationSweden,
			"italien":                   etfscraper.LocationItaly,
			"italy":                     etfscraper.LocationItaly,
			"spanien":                   etfscraper.LocationSpain,
			"spain":                     etfscraper.LocationSpain,
			"irland":                    etfscraper.LocationIreland,
			"ireland":                   etfscraper.LocationIreland,
			"dänemark":                  etfscraper.LocationDenmark,
			"denmark":                   etfscraper.LocationDenmark,
			"finnland":                  etfscraper.LocationFinland,
			"finland":                   etfscraper.LocationFinland,
			"türkei":                    etfscraper.LocationTurkey,
			"turkey":                    etfscraper.LocationTurkey,
			"belgien":                   etfscraper.LocationBelgium,
			"belgium":                   etfscraper.LocationBelgium,
			"österreich":                etfscraper.LocationAustria,
			"austria":                   etfscraper.LocationAustria,
			"luxemburg":                 etfscraper.LocationLuxembourg,
			"luxembourg":                etfscraper.LocationLuxembourg,
			"singapur":                  etfscraper.LocationSingapore,
			"singapore":                 etfscraper.LocationSingapore,
			"norwegen":                  etfscraper.LocationNorway,
			"norway":                    etfscraper.LocationNorway,
			"israel":                    etfscraper.LocationIsrael,
			"europäische union":         etfscraper.LocationEurope,
			"european union":            etfscraper.LocationEurope,
			"bargeld und/oder derivate": etfscraper.LocationCash,
		},
		MonthTranslations: map[string]string{
			// Full German month names (must be matched before abbreviations)
			"Januar":    "Jan",
			"Februar":   "Feb",
			"März":      "Mar",
			"April":     "Apr",
			"Mai":       "May",
			"Juni":      "Jun",
			"Juli":      "Jul",
			"August":    "Aug",
			"September": "Sep",
			"Oktober":   "Oct",
			"November":  "Nov",
			"Dezember":  "Dec",
			// Abbreviated forms
			"Jan": "Jan",
			"Feb": "Feb",
			"Mär": "Mar",
			"Apr": "Apr",
			"Jun": "Jun",
			"Jul": "Jul",
			"Aug": "Aug",
			"Sep": "Sep",
			"Okt": "Oct",
			"Nov": "Nov",
			"Dez": "Dec",
		},
		DateFormats:        []string{"02.Jan.2006", "02.Jan2006"},
		DateHeaderPatterns: []string{"Fondsposition per", "Fondsbestände am"},
		ColumnMappings: ColumnMapper{
			Name:           []string{"Name"},
			Ticker:         []string{"Emittententicker"},
			ISIN:           []string{"ISIN"},
			MarketValue:    []string{"Marktwert"},
			Weight:         []string{"Gewichtung (%)"},
			Quantity:       []string{"Nominale"},
			Price:          []string{"Kurs"},
			Sector:         []string{"Sektor"},
			AssetClass:     []string{"Anlageklasse"},
			Location:       []string{"Standort"},
			Exchange:       []string{"Börse"},
			Currency:       []string{"Währung"},
			MarketCurrency: []string{"Marktwährung"},
		},
	},
	"uk": {
		DiscoveryURL:        "https://www.ishares.com/uk/individual/en/product-screener/product-screener-v3.1.jsn?dcrPath=/templatedata/config/product-screener-v3/data/en/uk/product-screener/ishares-product-screener-backend-config&siteEntryPassthrough=true",
		BaseURL:             "https://www.ishares.com",
		HoldingsURLTemplate: "%s%s/fund/1506575576011.ajax?fileType=csv",
		DefaultCurrency:     etfscraper.CurrencyGBP,
		DefaultExchange:     etfscraper.ExchangeLSE,
		AssetClassMapping: map[string]etfscraper.AssetClass{
			"equity":         etfscraper.AssetClassEquity,
			"fixed income":   etfscraper.AssetClassBond,
			"cash":           etfscraper.AssetClassCash,
			"commodity":      etfscraper.AssetClassCommodity,
			"real estate":    etfscraper.AssetClassRealEstate,
			"digital assets": etfscraper.AssetClassCryptocurrency,
			"multi asset":    etfscraper.AssetClassAlternative,
		},
		SectorMapping: map[string]etfscraper.Sector{
			"energy":                 etfscraper.SectorEnergy,
			"materials":              etfscraper.SectorMaterials,
			"industrials":            etfscraper.SectorIndustrials,
			"consumer discretionary": etfscraper.SectorConsumerDiscretionary,
			"consumer staples":       etfscraper.SectorConsumerStaples,
			"health care":            etfscraper.SectorHealthcare,
			"financials":             etfscraper.SectorFinancials,
			"information technology": etfscraper.SectorInformationTechnology,
			"communication":          etfscraper.SectorTelecommunication,
			"utilities":              etfscraper.SectorUtilities,
			"real estate":            etfscraper.SectorRealEstate,
		},
		LocationMapping: map[string]etfscraper.Location{
			"united states":           etfscraper.LocationUnitedStates,
			"united kingdom":          etfscraper.LocationUnitedKingdom,
			"japan":                   etfscraper.LocationJapan,
			"germany":                 etfscraper.LocationGermany,
			"france":                  etfscraper.LocationFrance,
			"switzerland":             etfscraper.LocationSwitzerland,
			"canada":                  etfscraper.LocationCanada,
			"australia":               etfscraper.LocationAustralia,
			"china":                   etfscraper.LocationChina,
			"taiwan":                  etfscraper.LocationTaiwan,
			"south korea":             etfscraper.LocationSouthKorea,
			"india":                   etfscraper.LocationIndia,
			"brazil":                  etfscraper.LocationBrazil,
			"netherlands":             etfscraper.LocationNetherlands,
			"sweden":                  etfscraper.LocationSweden,
			"italy":                   etfscraper.LocationItaly,
			"spain":                   etfscraper.LocationSpain,
			"ireland":                 etfscraper.LocationIreland,
			"denmark":                 etfscraper.LocationDenmark,
			"finland":                 etfscraper.LocationFinland,
			"turkey":                  etfscraper.LocationTurkey,
			"belgium":                 etfscraper.LocationBelgium,
			"austria":                 etfscraper.LocationAustria,
			"luxembourg":              etfscraper.LocationLuxembourg,
			"singapore":               etfscraper.LocationSingapore,
			"norway":                  etfscraper.LocationNorway,
			"israel":                  etfscraper.LocationIsrael,
			"cash and/or derivatives": etfscraper.LocationCash,
		},
		MonthTranslations:  nil,
		DateFormats:        []string{"02/Jan/2006"},
		DateHeaderPatterns: []string{"Fund Holdings as of"},
		ColumnMappings: ColumnMapper{
			Name:           []string{"Name"},
			Ticker:         []string{"Ticker"},
			ISIN:           []string{"ISIN"},
			MarketValue:    []string{"Market Value"},
			Weight:         []string{"Weight (%)", "Market Weight"},
			Quantity:       []string{"Quantity"},
			Price:          []string{"Price"},
			Sector:         []string{"Sector"},
			AssetClass:     []string{"Asset Class"},
			Location:       []string{"Location"},
			Exchange:       []string{"Exchange"},
			Currency:       []string{"Currency"},
			MarketCurrency: []string{"Market Currency"},
		},
	},
	"fr": {
		DiscoveryURL:        "https://www.blackrock.com/fr/particuliers/product-screener/product-screener-v3.1.jsn?dcrPath=/templatedata/config/product-screener-v3/data/fr/France/product-screener-backend-config&siteEntryPassthrough=true",
		BaseURL:             "https://www.blackrock.com",
		HoldingsURLTemplate: "%s%s/1499538099380.ajax?fileType=csv",
		DefaultCurrency:     etfscraper.CurrencyEUR,
		DefaultExchange:     etfscraper.ExchangeEuronext,
		AssetClassMapping: map[string]etfscraper.AssetClass{
			"actions":            etfscraper.AssetClassEquity,
			"obligations":        etfscraper.AssetClassBond,
			"liquidités":         etfscraper.AssetClassCash,
			"matières premières": etfscraper.AssetClassCommodity,
			"immobilier":         etfscraper.AssetClassRealEstate,
			"digital assets":     etfscraper.AssetClassCryptocurrency,
			"multi-actifs":       etfscraper.AssetClassAlternative,
			"marchés privés":     etfscraper.AssetClassAlternative,
		},
		SectorMapping: map[string]etfscraper.Sector{
			"energie":                         etfscraper.SectorEnergy,
			"matériaux":                       etfscraper.SectorMaterials,
			"industries":                      etfscraper.SectorIndustrials,
			"biens de consommation cycliques": etfscraper.SectorConsumerDiscretionary,
			"biens de consommation de base":   etfscraper.SectorConsumerStaples,
			"santé":                           etfscraper.SectorHealthcare,
			"finance":                         etfscraper.SectorFinancials,
			"technologie de l'information":    etfscraper.SectorInformationTechnology,
			"la communication":                etfscraper.SectorTelecommunication,
			"services publics":                etfscraper.SectorUtilities,
			"immobilier":                      etfscraper.SectorRealEstate,
		},
		LocationMapping: map[string]etfscraper.Location{
			"états-unis":                     etfscraper.LocationUnitedStates,
			"etats-unis":                     etfscraper.LocationUnitedStates,
			"royaume-uni":                    etfscraper.LocationUnitedKingdom,
			"japon":                          etfscraper.LocationJapan,
			"allemagne":                      etfscraper.LocationGermany,
			"france":                         etfscraper.LocationFrance,
			"suisse":                         etfscraper.LocationSwitzerland,
			"canada":                         etfscraper.LocationCanada,
			"australie":                      etfscraper.LocationAustralia,
			"chine":                          etfscraper.LocationChina,
			"taïwan":                         etfscraper.LocationTaiwan,
			"corée du sud":                   etfscraper.LocationSouthKorea,
			"inde":                           etfscraper.LocationIndia,
			"brésil":                         etfscraper.LocationBrazil,
			"pays-bas":                       etfscraper.LocationNetherlands,
			"suède":                          etfscraper.LocationSweden,
			"italie":                         etfscraper.LocationItaly,
			"espagne":                        etfscraper.LocationSpain,
			"irlande":                        etfscraper.LocationIreland,
			"danemark":                       etfscraper.LocationDenmark,
			"denmark":                        etfscraper.LocationDenmark,
			"finlande":                       etfscraper.LocationFinland,
			"finland":                        etfscraper.LocationFinland,
			"turquie":                        etfscraper.LocationTurkey,
			"turkey":                         etfscraper.LocationTurkey,
			"belgique":                       etfscraper.LocationBelgium,
			"belgium":                        etfscraper.LocationBelgium,
			"autriche":                       etfscraper.LocationAustria,
			"austria":                        etfscraper.LocationAustria,
			"luxembourg":                     etfscraper.LocationLuxembourg,
			"singapour":                      etfscraper.LocationSingapore,
			"singapore":                      etfscraper.LocationSingapore,
			"norvège":                        etfscraper.LocationNorway,
			"norway":                         etfscraper.LocationNorway,
			"israël":                         etfscraper.LocationIsrael,
			"israel":                         etfscraper.LocationIsrael,
			"espèces et/ou produits dérivés": etfscraper.LocationCash,
		},
		MonthTranslations: map[string]string{
			"janv.": "Jan",
			"févr.": "Feb",
			"mars":  "Mar",
			"avr.":  "Apr",
			"mai":   "May",
			"juin":  "Jun",
			"juil.": "Jul",
			"août":  "Aug",
			"sept.": "Sep",
			"oct.":  "Oct",
			"nov.":  "Nov",
			"déc.":  "Dec",
		},
		DateFormats:        []string{"02/Jan/2006"},
		DateHeaderPatterns: []string{"Fund Holdings as of"},
		ColumnMappings: ColumnMapper{
			Name:           []string{"Name"},
			Ticker:         []string{"Ticker"},
			ISIN:           []string{"ISIN"},
			MarketValue:    []string{"Market Value"},
			Weight:         []string{"Weight (%)", "Market Weight"},
			Quantity:       []string{"Shares", "Quantity"},
			Price:          []string{"Price"},
			Sector:         []string{"Sector"},
			AssetClass:     []string{"Asset Class"},
			Location:       []string{"Location"},
			Exchange:       []string{"Exchange"},
			Currency:       []string{"Currency"},
			MarketCurrency: []string{"Market Currency"},
		},
	},
}

func SupportedRegions() []string {
	regions := make([]string, 0, len(regionConfigs))
	for region := range regionConfigs {
		regions = append(regions, region)
	}

	sort.Strings(regions)
	return regions
}
